services:
  backend:
    image: sid0014/climate-event-aggregator:backend-latest
    # For local builds:
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      simulator:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - WEBSOCKET_URL=ws://simulator:8765
      - NODE_ENV=local
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - climate-net

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - climate-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  simulator:
    image: sid0014/climate-event-aggregator:simulator-latest
    # For local builds:
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile.simulator
    ports:
      - "8765:8765"
    networks:
      - climate-net
    healthcheck:
      test: ["CMD", "bash", "-c", "</dev/tcp/localhost/8765"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  frontend:
    image: sid0014/climate-event-aggregator:frontend-latest
    # For local builds:
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - climate-net

networks:
  climate-net:
